name: tracker
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  http: ^1.4.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  infinite_scroll_pagination: ^5.1.0
  flutter_bloc: ^9.1.1
  persistent_bottom_nav_bar_v2: ^6.0.1
  get_it: ^8.0.3
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/noData.json
    - assets/animation/Animation - 1750527560023.json

  fonts:
    - family: MyriadArabic
      fonts:
        - asset: assets/fonts/MyriadArabicBold.otf
          weight: 700
        - asset: assets/fonts/MyriadArabicRegular.otf
          weight: 400
        - asset: assets/fonts/MyriadArabicSemibold.otf
          weight: 600
        - asset: assets/fonts/MyriadArabicIt.otf
          weight: 500
